"""Auto migration

Revision ID: 0463587f10ba
Revises: 5a428a5740ec
Create Date: 2026-04-25 16:18:24.953799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0463587f10ba'
down_revision = '5a428a5740ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###