"""Auto migration

Revision ID: 15ded8bde180
Revises: a7fbc45d94e1
Create Date: 2026-08-16 06:29:26.844681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ded8bde180'
down_revision = 'a7fbc45d94e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###