"""Auto migration

Revision ID: 1ea7c566c4c5
Revises: e63c1df5eabc
Create Date: 2026-04-25 16:25:46.746325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea7c566c4c5'
down_revision = 'e63c1df5eabc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###