"""Auto migration

Revision ID: 27ca6967dc02
Revises: f93d53709244
Create Date: 2026-08-16 10:57:57.265817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ca6967dc02'
down_revision = 'f93d53709244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###