"""Auto migration

Revision ID: 56b0915d2651
Revises: 27ca6967dc02
Create Date: 2026-08-17 19:57:22.333522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b0915d2651'
down_revision = '27ca6967dc02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###