"""Auto migration

Revision ID: 5a428a5740ec
Revises: 7dc78d661e21
Create Date: 2026-04-25 13:32:15.109125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a428a5740ec'
down_revision = '7dc78d661e21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###