"""Auto migration

Revision ID: 5a69f042b7b7
Revises: 15ded8bde180
Create Date: 2026-08-16 10:56:34.754945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a69f042b7b7'
down_revision = '15ded8bde180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###