"""Auto migration

Revision ID: 61eb88abb0ec
Revises: 1ea7c566c4c5
Create Date: 2026-04-25 16:28:01.715433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61eb88abb0ec'
down_revision = '1ea7c566c4c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###