"""Auto migration

Revision ID: 87eed871ba32
Revises: 61eb88abb0ec
Create Date: 2026-04-25 16:34:49.386623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87eed871ba32'
down_revision = '61eb88abb0ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###