"""Auto migration

Revision ID: 924f5dab516a
Revises: a1263e31f76e
Create Date: 2026-08-10 05:49:47.194560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924f5dab516a'
down_revision = 'a1263e31f76e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('template_id', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('targets', sa.Text(), nullable=True))
    op.add_column('scans', sa.Column('folder', sa.String(), nullable=True))
    op.add_column('scans', sa.Column('schedule', sa.String(), nullable=True))
    op.alter_column('scans', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('scans', 'schedule')
    op.drop_column('scans', 'folder')
    op.drop_column('scans', 'targets')
    op.drop_column('scans', 'template_id')
    # ### end Alembic commands ###