"""Auto migration

Revision ID: a1263e31f76e
Revises: 03697e0ad6a4
Create Date: 2026-08-05 06:29:03.299089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1263e31f76e'
down_revision = '03697e0ad6a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###