"""Auto migration

Revision ID: a7fbc45d94e1
Revises: 924f5dab516a
Create Date: 2026-08-11 12:00:16.935114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fbc45d94e1'
down_revision = '924f5dab516a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###