"""Auto migration

Revision ID: e63c1df5eabc
Revises: 0463587f10ba
Create Date: 2026-04-25 16:23:11.489363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63c1df5eabc'
down_revision = '0463587f10ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###