"""Auto migration

Revision ID: f93d53709244
Revises: 5a69f042b7b7
Create Date: 2026-08-16 10:56:53.461595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93d53709244'
down_revision = '5a69f042b7b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###